[env:cyd]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
  -DUSER_SETUP_LOADED
lib_deps =
  bodmer/TFT_eSPI@^2.5.43
  bblanchon/ArduinoJson@^7.0.0
  paulstoffregen/XPT2046_Touchscreen@^1.4.0
  arduino-libraries/NTPClient@^3.2.1
